package models.ai;

import java.time.LocalDateTime;

/**
 * Represents a single message turn in the AI Study Assistant chat.
 * Role is either "USER" (student input) or "ASSISTANT" (AI response).
 * Mapped to the {@code ai_chat_messages} database table.
 */
public class ChatMessage {

    /** Role constant for student messages. */
    public static final String ROLE_USER      = "USER";
    /** Role constant for AI-generated messages. */
    public static final String ROLE_ASSISTANT = "ASSISTANT";

    private int           id;
    private int           studentId;
    private int           courseId;
    private String        role;
    private String        messageText;
    private boolean       isFavorite;
    private LocalDateTime createdAt;

    // ── Constructors ──────────────────────────────────────────────────────────

    /** No-arg constructor required for JDBC mapping. */
    public ChatMessage() {
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Full constructor for creating a new message before persistence.
     *
     * @param studentId   ID of the student who owns this message
     * @param courseId    ID of the course this message belongs to
     * @param role        {@link #ROLE_USER} or {@link #ROLE_ASSISTANT}
     * @param messageText The message content
     */
    public ChatMessage(int studentId, int courseId, String role, String messageText) {
        this.studentId   = studentId;
        this.courseId    = courseId;
        this.role        = role;
        this.messageText = messageText;
        this.isFavorite  = false;
        this.createdAt   = LocalDateTime.now();
    }

    /**
     * Full constructor including all persisted fields (used when loading from DB).
     *
     * @param id          Database primary key
     * @param studentId   ID of the student who owns this message
     * @param courseId    ID of the course this message belongs to
     * @param role        {@link #ROLE_USER} or {@link #ROLE_ASSISTANT}
     * @param messageText The message content
     * @param isFavorite  Whether the student has marked this message as a favorite
     * @param createdAt   Timestamp when the message was created
     */
    public ChatMessage(int id, int studentId, int courseId, String role,
                       String messageText, boolean isFavorite, LocalDateTime createdAt) {
        this.id          = id;
        this.studentId   = studentId;
        this.courseId    = courseId;
        this.role        = role;
        this.messageText = messageText;
        this.isFavorite  = isFavorite;
        this.createdAt   = createdAt;
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public int getId()                          { return id; }
    public void setId(int id)                   { this.id = id; }

    public int getStudentId()                   { return studentId; }
    public void setStudentId(int studentId)     { this.studentId = studentId; }

    public int getCourseId()                    { return courseId; }
    public void setCourseId(int courseId)       { this.courseId = courseId; }

    public String getRole()                     { return role; }
    public void setRole(String role)            { this.role = role; }

    public String getMessageText()              { return messageText; }
    public void setMessageText(String text)     { this.messageText = text; }

    public boolean isFavorite()                 { return isFavorite; }
    public void setFavorite(boolean favorite)   { this.isFavorite = favorite; }

    public LocalDateTime getCreatedAt()         { return createdAt; }
    public void setCreatedAt(LocalDateTime t)   { this.createdAt = t; }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /** Returns {@code true} if this message was sent by the student. */
    public boolean isUserMessage()              { return ROLE_USER.equals(role); }

    /** Returns {@code true} if this message was generated by the AI assistant. */
    public boolean isAssistantMessage()         { return ROLE_ASSISTANT.equals(role); }

    @Override
    public String toString() {
        return "ChatMessage{id=" + id
                + ", studentId=" + studentId
                + ", courseId=" + courseId
                + ", role='" + role + "'"
                + ", favorite=" + isFavorite
                + ", createdAt=" + createdAt + "}";
    }
}
